mqtt:
  addr: "tcp://broker:1883"
  clientId: "room-sensor-1"
  topic: "sensors/room"
  intervalMs: 1000
sensors:
  - label: "temperature"
    min: 15.0
    max: 35.0
    step: 0.5
    initial: 25.0
    integer: false
  - label: "co2Level"
    min: 450
    max: 1200
    step: 50
    initial: 600
    integer: true
