/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.path.variable.mqtt.pub.demo;

import com.path.variable.mqtt.pub.demo.publisher.MqttPublisher;
import com.path.variable.mqtt.pub.demo.publisher.TemperatureReport;
import com.path.variable.mqtt.pub.demo.sensor.TemperatureSensor;

public class App {

    public void run() {
        var sensor = new TemperatureSensor();
        var publisher = new MqttPublisher("tcp://127.0.0.1:1883", "temperature-pub");
        while (true) {
            var report = new TemperatureReport(sensor.getTemperature());
            publisher.publish(report);
            try {
                Thread.sleep(1000);
            } catch (InterruptedException e) {
                throw new RuntimeException(e);
            }
        }
    }


    public static void main(String[] args) {
        new App().run();
    }
}
