/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.path.variable.mqtt.pub.demo;

import com.path.variable.mqtt.pub.demo.publisher.MqttPublisher;
import com.path.variable.mqtt.pub.demo.sensor.Co2Sensor;
import com.path.variable.mqtt.pub.demo.sensor.TemperatureSensor;
import com.path.variable.mqtt.pub.demo.sensor.report.RoomReport;

import static java.lang.Thread.sleep;

public class App {

    public void run() {
        final var temperatureSensor = new TemperatureSensor();
        final var co2Sensor = new Co2Sensor();
        final var publisher = new MqttPublisher(System.getenv("MQTT_ADDR"), "room-sensor");
        while (true) {
            var report = new RoomReport(temperatureSensor.getTemperature(), co2Sensor.getCo2Level());
            publisher.publish(report, "living-room");
            try {
                sleep(1000);
            } catch (InterruptedException e) {
                throw new RuntimeException(e);
            }
        }
    }


    public static void main(String[] args) {
        new App().run();
    }
}
