name: CI

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  build:
    name: Build and test with Java 21
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Build with Gradle
        run: |
            ./gradlew --no-daemon --console=plain build

      - name: Upload test reports
        uses: actions/upload-artifact@v4
        with:
          name: test-results-21
          path: |
            **/build/test-results/
            **/build/reports/tests/
